hasuraSecret: "@rt3m1s."
jwtSecret: 44fe431cdc896ccab691ad0599f4e0a12690ce1ededebe57b825823bc6b4d24f
flaskSecret: 76f8bae45e807865955344c1a58882d38c8ceb4f855f58091642b7d48290af97
passwordSalt: 06a4b397fc7045eac527c2aec3ff46cee5ce30016c760f238c26e79902fe67b6
privKey: |-
  -----BEGIN PRIVATE KEY-----
  MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQDS4QL2IaWQPTRp
  UFKDphTLrwTsotclyStbw50JsG5swV6An9ERCTqwFUV0yCIwSjNPGkEfDBfNyVw+
  hlgfwlPP5IkoRocn4AhWFbAkFPYv/dT8K8KSWCmIopOgR4rHnfOFKO8Mjh8JlTJh
  gKc6JY8BgkPALnVWmYFLP17KoCK21roQ+AbQA5B9zl1lyVnSIfp4Deq8BbBrY4aJ
  5L+UQd753h3QNNYE4i1/8cun1RFOgYjLVDhGWxIygz3T83p3hub3V3wACyrj//9B
  brJupyX8CoxCC00bFSQM3kKBRMuAXYpMH6Fsqc18a1BNqlyT4YI+NvLH12ZqV/G0
  xxdqOQ1ClfokQxFIkmxGm2hPXC7hdVRLdwSrDIHZ46IRaNzhliHF9MpRsXAgimFS
  IqiLYhMgWUngD2AtM0As/tWZF676qXPOunTU98ypwtONVrh5SWnKy3hpPw42Buew
  xT0ZmP52xWBh6WrE5gY46nUHlEIZBihVEDVcNcOYeBP2pKWlpSOY9KirjBzIyEL8
  KsG/VF5cg42w+b0WfSC0JFq/rSeGe6kKsdlZTWzozJ++R4ji255GYGVeJ/Mj2kCp
  Cb9WJmJjsUIQsAyb258UBwOOCF6TZXVSW68sYKxTiubvmKjR+6jkh9qoNWTVY8uh
  TMMt6ZvNaE4FghwYNfS3nPtPCnb+mQIDAQABAoICAQC4fzjSEtoBeirywN2QZKvp
  EHUke8v0OS8AGAK6yWuzJvMBYdHOL97y04lzBO40hZaibHvxJ+ljl/pmka9kCea+
  ClqdrCbvkih4+Hyk9Nn3XwMKpVaUJyIfcu3p2u3me6DlLc0HlQg+oBP2DlNAoj+d
  uFSCPaNXYvIl3YmXiccVZIRh+D4tnBC8oOJB/YniOOwkQTjPy8JwEiFRX5rloUPu
  JJC86p0cpK3eNLRTYCzGHLqL+mFJ3L/tBboASBMrpBFK8XWBrEOYOw8eNjVSblbj
  Tm8sESsiuLpTr9lLs96/rhcjRsE6is1HP7SAXr6kezYyLGz4vtHR1KOZ4F3yB3w6
  39SbAgVsnUo3AW8saPheVKKZsssh5npG5GcqWDpKFY2qfZmjsisvQa14sOycdHXe
  1m8D+uXljeSKVzrapVAQuKxOk7E/jzLAn0p8y/7q4Ia4j6UDs48L/20zj9MLXw/N
  bCulOP7y0O2uRQ3Up7jw4C0+gnMGSRqb+hA6hJ9bLjVlQln/H1wMwXLsibTNPOT5
  zLv1CWc2yPVHpLXAdUG82HrP1pQGBJpA5PsPfbSphdoEOj4HeO49koYE8AGMj3pU
  +KrZLDU2jq0MT97sAZkMdM+8ypkCbDHo5+SQ14ExHS4mgUkUQwgtE94IqpvYqqxU
  dPYi8SP6lNVjn/JC0pB9AQKCAQEA+ZxDCJ1uSnUX4rKdMsFz06dLGL/71pMV5fRS
  rbaYyAI+bMP7b3XeuYeST5ImuQ5kraAx44FSIRAeXresliCg7BRimwqZgjA1Q8nL
  8bxHtW4yaQwr/DOymWQZEaYLiPisWWo3SvQeDep1OdCaJN+QdjZYnAgVB9hRgFvZ
  UBXbpDMdbkW+temH9HnZydoooRYotTnHP0aI5hA+9Uz3rW6piOA/Nkk4TgnlTqVZ
  x8MrSKpyBVXh+yCPucdRL14DXnL1DyNX4tQ4m8ci/GAQX98ltx+dfkX6IuXmxHzw
  rCXg7xzrBxRoF2bGRbpQ5sRF/biEZOqEE8GQSj17R4mMyTGEEQKCAQEA2Ebvp9ZJ
  59qEeR83c7DQPFAUWuzJxxcFyhe527ZumHU8D/wdpUB7NflXG0JEQlrBEAf3FMeF
  W4+g6ye2DZ8BAQJYM3QclEYQGgN+1zi5DxrH+iMS5+vLQS6/uljULBChBAa7wZ5B
  Qz4Q9ChoKOWtrWBaDeQ2qwtSBPXy5LzwAnRvqu3lu1Exf2Bh35lzh0I1I0QuI+I7
  sBoyeLUESVPA+u351FvO6i/Zjbrdr9tmwDNIQCedJcBufpfCbTSzOVhOpLFIVrcO
  6SPIzRUA1tibb7hhGsjINPyqryew4TKZnlndF4PoABOdSK7mS4/lxqpKxD7Zs9R7
  gU/ZCma8gnW6CQKCAQA1WikZ1kyUraKFWhgvmRngy4lJqP9zRc0QccCaUMUnOxOM
  u/cqQ89vaILlbx/HvkPWuL7xGdssJf3X0PqavC6pR1IsQX++S/+WlbN53/yT0xID
  Ug60wXgTQUn6c7tTc5OjKQjYhIVIBC06RlQsPXzrR4J5F2EnZB1HilpQu9tOpX5M
  66tvxpLAtqrOckrs44ef9NGZvMHWKvLKC8GE2Hp0PzpDqDLYu1TAEqe2AwllZsko
  SssamkMeOnQn47hkn72xlqRaX3IaGd5ogz/8vf2ZvrAzJVHp06oXpXzrzszdTxkN
  UldNaTJIBSL1sE4lhSMHTvkcH+tvcuS+za/B8UuBAoIBAQCFKwBrpo1xHmKNNcRu
  DsPZLzGpXr1LQgjFi+BbwbPNWfo2mXUjiFWVQUb6OM5Q0RKpLU5c1BFv9DsQMC5v
  qqTymx/15pumTJGjgt155apE+6eAhFIizVQkeYWCVymlTEPod8DqEeh7X98Oh0bD
  T9ClvXsVrJxgqyLAfTQm1ZMu38TWSY83zGGe3ZjGFfVFpmWTpmqGm8lGwIqtOkA+
  ajycBSXcNP9twTLCivnvSze0Rp9JKVsgoKEof4cuuNFWEOKzk5lIE4Ux1l/QrwsK
  PutOWggodtKXla//E4Bc2UwvbYOt9AFI8srYsyCIDD1eGwLYXR6tFLtLPwAT4HhY
  F+cJAoIBAQDv7mmTazHbORVwQngLUOpGwUVUyFhaadue/SWdk8D88RafUvm6DR72
  XSqV62OsF46Iqv2ogS+UlU+jFr3a3AGkHUuFwF3WSZ8IrxCecy1IAaOH1Oe6hd3c
  A/Af6iKNy4iHH3LEy5fgLsTz6c+9NvBTYlgCHHRH1sqbOjHMGam4dMaC0sBKGkLD
  U8P8Oi3z+k89z06ycaYJPmpAkd8Z9fC0yi5pCTggDHAqijD2wqXPBX2cZu0SzJHS
  3x2Zf4pwadiJjjX06X1ZUUI8Kdk/Mmzyn+oPB/VDL0tp6VjvjRSGAC6Il3WXVFPl
  i1VRQWKH0Bt4xqbM7a912eTXf/HX5cEh
  -----END PRIVATE KEY-----
certificate: |-
  -----BEGIN CERTIFICATE-----
  MIIFoDCCA4gCCQCTF8YECfKcZTANBgkqhkiG9w0BAQsFADCBkTELMAkGA1UEBhMC
  R1IxDjAMBgNVBAgMBUNyZXRlMRIwEAYDVQQHDAlIZXJha2xpb24xDjAMBgNVBAoM
  BUZPUlRIMRIwEAYDVQQLDAlJQ1MtRk9SVEgxFTATBgNVBAMMDEFSVEVNSVMgVEVT
  VDEjMCEGCSqGSIb3DQEJARYUZ2tpZ2tpc0BpY3MuZm9ydGguZ3IwHhcNMTgwOTI3
  MTc1NDM5WhcNMTkwOTI3MTc1NDM5WjCBkTELMAkGA1UEBhMCR1IxDjAMBgNVBAgM
  BUNyZXRlMRIwEAYDVQQHDAlIZXJha2xpb24xDjAMBgNVBAoMBUZPUlRIMRIwEAYD
  VQQLDAlJQ1MtRk9SVEgxFTATBgNVBAMMDEFSVEVNSVMgVEVTVDEjMCEGCSqGSIb3
  DQEJARYUZ2tpZ2tpc0BpY3MuZm9ydGguZ3IwggIiMA0GCSqGSIb3DQEBAQUAA4IC
  DwAwggIKAoICAQDS4QL2IaWQPTRpUFKDphTLrwTsotclyStbw50JsG5swV6An9ER
  CTqwFUV0yCIwSjNPGkEfDBfNyVw+hlgfwlPP5IkoRocn4AhWFbAkFPYv/dT8K8KS
  WCmIopOgR4rHnfOFKO8Mjh8JlTJhgKc6JY8BgkPALnVWmYFLP17KoCK21roQ+AbQ
  A5B9zl1lyVnSIfp4Deq8BbBrY4aJ5L+UQd753h3QNNYE4i1/8cun1RFOgYjLVDhG
  WxIygz3T83p3hub3V3wACyrj//9BbrJupyX8CoxCC00bFSQM3kKBRMuAXYpMH6Fs
  qc18a1BNqlyT4YI+NvLH12ZqV/G0xxdqOQ1ClfokQxFIkmxGm2hPXC7hdVRLdwSr
  DIHZ46IRaNzhliHF9MpRsXAgimFSIqiLYhMgWUngD2AtM0As/tWZF676qXPOunTU
  98ypwtONVrh5SWnKy3hpPw42BuewxT0ZmP52xWBh6WrE5gY46nUHlEIZBihVEDVc
  NcOYeBP2pKWlpSOY9KirjBzIyEL8KsG/VF5cg42w+b0WfSC0JFq/rSeGe6kKsdlZ
  TWzozJ++R4ji255GYGVeJ/Mj2kCpCb9WJmJjsUIQsAyb258UBwOOCF6TZXVSW68s
  YKxTiubvmKjR+6jkh9qoNWTVY8uhTMMt6ZvNaE4FghwYNfS3nPtPCnb+mQIDAQAB
  MA0GCSqGSIb3DQEBCwUAA4ICAQCc5lX5+E/QcrAnZsLDD/jPD1PRXKcb1Elpyf13
  kN+IHsD6I6oVYfHrUIsGQuiv8eEFDCueQkrQdHRXcVXLIdyuBq1lGuzZRha2eJba
  1KYkGzNTvyEYoaHHUgrIJ6/xPWTMfwr31Wco93kxO6RqBJQWuk4hIeNqvjuYlwKD
  nVbBjcvx0UZG+Bu/jY0ZVWp1HcQjd9D9KDnUaR+1sVRrQFl3xoIFe9ExbPIpWOV8
  jxocKRuOrn3lNKeg8lLKuP5l56y3jdQIAeEGmGAIdltYH9pWeEuiGJSo/lkit12E
  NyfYEC9s8EfDK0jh/Cnze4ycXxq58LdlMzETxDq2n2wZ8JnDrnixZ77RqDg0d2rK
  juJFx7eIlHym3JOJEdfJNZXJ3QAkpuX9qR2U7za5ejj3Z1uus74vGJEdmwMnOvmr
  9KWuo4PjFjTaEF3uwewu3bqZnqoryrjJPYitctRKDZg3gY49qFI+fn8LKwJ8E8Un
  IUIJTtkNcESXY/DDAskYjPyiyUcMDNVwAX39AiOQjqVAUkCuizExCbPocTDxJfP/
  JfB+voPc7jkkFzNOy2OLklRpeqNij5U6+/z2+04cpv+zMqMekiQPiC/Guo4dOqve
  jvzLR/IpylBvHWyql8eu+vek8Xwzrmwsjit3xrIGLScm3navwzWm4gXtOSou6jVl
  /RhKCg==
  -----END CERTIFICATE-----
