site_name: Artemis Docs
nav:
    -   Home: index.md
    -   Getting Started:
            -   'Logic and Microservices': logic.md
            -   'Technical Requirements': requirements.md
            -   'First Steps': gettingstarted.md
            -   'Installation and Setup': installsetup.md
            -   'Running ARTEMIS': running.md
            -   'Web Application': webapp.md
            -   'Upgrading': upgrade.md
            -   'Best Practices': bestpractices.md
    -   Configuration:
            -   Basic: basicconf.md
            -   'Environment Variables': envvars.md
            -   Frontend: frontendconf.md
            -   Logging: loggingconf.md
            -   LDAP: ldapconf.md
            -   'RPKI Validation': rpkivalidconf.md
            -   'ExaBGP Local Feed': exabgpfeed.md
    -   Details:
            -   'BGP Update Information': bgpupdateinfo.md
            -   'Hijack Information': hijackinfo.md
            -   Redis: redisinfo.md
    -   Advanced:
            -   'Scaling Microservices' : scaling.md
            -   'Auto-Configuration': autoconfiguration.md
            -   'Auto-Mitigation': automitigation.md
            -   'Replaying History': history.md
            -   'Community Annotations': commannotations.md
            -   'Database restore': dbrestore.md
            -   'Decoupling Microservices': decouplingmicroservices.md
            -   'Grafana Dashboard': grafanadash.md
            -   'Private BMP feeds': bgpstreambmp.md
            -   Vagrant: vagrant.md
            -   Architecture: architecture.md
    -   Kubernetes: kubernetes.md
    -   APIs:
            -   GraphQL: graphqlapi.md
    -   FAQ: faq.md
    -   Issues and Fixes: issuesfixes.md
    -   Changelog: changelog.md
theme:
    name: material
    favicon: images/artemis_icon.png
markdown_extensions:
    - mdx_truly_sane_lists
    - pymdownx.superfences
    - markdown.extensions.tables
    - pymdownx.saneheaders
    - pymdownx.tasklist
    - pymdownx.emoji
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.magiclink
google_analytics:
    - UA-55317739-7
    - auto
