{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-frontend-ingress
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.ingress.frontend.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{ include "artemis.ingress.rewrite" . | indent 4 }}
  labels:
{{ include "artemis.labels" . | indent 4 }}
spec:
  {{- if .Values.ingress.tlsEnabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host | default "artemis.com" }}
    secretName: {{ .Release.Name }}-secret-tls
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host | default "artemis.com" }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-{{ .Values.webappHost }}-svc
          servicePort: {{ .Values.webappPort }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-graphql-ingress
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.ingress.graphql.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{ include "artemis.ingress.rewrite" . | indent 4 }}
  labels:
{{ include "artemis.labels" . | indent 4 }}
spec:
  {{- if .Values.ingress.tlsEnabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host | default "artemis.com" }}
    secretName: {{ .Release.Name }}-secret-tls
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host | default "artemis.com" }}
    http:
      paths:
      - path: /api/graphql
        backend:
          serviceName: {{ .Release.Name}}-{{ .Values.hasuraHost }}-svc
          servicePort: {{ .Values.hasuraPort }}
{{- end -}}
