apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: postgrest
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-postgrest
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgrest
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: wait-for-service
        image: busybox
        command: ['sh', '-c', 'until nc -z {{ .Values.dbHost }} {{ .Values.dbPort }}; do echo waiting for services; sleep 10; done;']
      containers:
      - env:
        - name: PGRST_DB_ANON_ROLE
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: dbUser
        - name: PGRST_DB_SCHEMA
          value: public
        - name: PGRST_DB_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: dbUri
        image: postgrest/postgrest:v5.2.0
        name: postgrest
        resources: {}
      restartPolicy: Always
status: {}
