#
# ARTEMIS Configuration File (sample, please do not use as-is)
#
# Defining a named variable:
#     named_variable: &named_variable
#         value_of_variable
# Use named variable:
#     *named_variable
# - denotes an entry
#
# Start of Prefix Definitions
prefixes:
    # A reference for a single prefix
    simple_prefix: &my_prefix
        A.B.C.D/24
    # A reference for a list of prefixes
    simple_prefix_list: &my_prefixes
        - X.Y.Z.W/23
        - K.L.M.N/24
        - O:P::/64
# End of Prefix Definitions
#
# Start of Monitor Definitions
monitors:
    riperis: ['']
    bgpstreamlive:
        - routeviews
        - ris
    betabmp:
        - betabmp
    exabgp:
        - ip: ip_to_exabgp_1
          port: port_1
        - ip: ip_to_exabgp_2
          port: port_2
    bgpstreamhist:
        - <csv_dir_with_formatted_BGP_updates>
# End of Monitor Definitions
#
# Start of ASN Definitions
asns:
    my_asn: &my_asn
        1234
    my_asns: &my_asns
        - 321
        - 432
    my_neighbor: &my_neighbor
        222
    my_neighbors: &my_neighbors
        - 333
        - 444
# End of ASN Definitions
#
# Start of Rule Definitions
rules:
# 1st Rule
- prefixes:
    - *my_prefix
  origin_asns:
    - *my_asn
  neighbors:
    - *my_neighbor
  mitigation:
    manual
# 2nd Rule
- prefixes:
    - *my_prefixes
    - other_prefix
  origin_asns:
    - *my_asns
    - *my_asn
    - 7895
  mitigation:
    manual
# Unannounced prefix rule
- prefixes:
    A.B.C.E/24
  mitigation:
      manual
# Note: Everything can be a list or a single element
# End of Rule Definitions
